CREATE TABLE GATEWAY(
	ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(255) NOT NULL,
	IPV4 VARCHAR(255) NOT NULL
);

CREATE TABLE DEVICE(
	UID VARCHAR(255) NOT NULL PRIMARY KEY,
	VENDOR VARCHAR(255) NOT NULL,
	CREATION_DATE DATE NOT NULL,
	STATUS BOOLEAN,
	GATEWAY_ID INT NOT NULL,
	FOREIGN KEY (GATEWAY_ID) REFERENCES GATEWAY(ID) ON DELETE CASCADE
);
